[package]
name = "pclass-parser"
version = "0.1.0"
authors = ["Phodal Huang <h@phodal.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dependencies.class-parser]
path = "class-parser"

[dependencies.classfile]
path = "classfile"

[workspace]
members = [
    "classfile",
]
